### ISSUE TITLE
Reasoning for inconsistency (or consistency) of input arguments

### ISSUE THREAD

**Issue by malramsay64** [pdebuyl-lab/tidynamics#11]
For your functions 
- `tidynamics.acf` takes `data`, the input signal
- `tidynamics.msd` takes `pos`, the input trajectory
- `tidynamics.cross_displacement` takes `x`, the input trajectory,

Using `pos` for `msd` does make sense. Should `x` be a conceptually different type of input data? If so, an explanation of each would be useful.

**Comment by pdebuyl** [comment]
`acf` is rather generic hence the `data` argument.

The `x` in `cross_displacement` is intended to be "positions", so I'll change only this one for consistency.
