### ISSUE TITLE
MSD Result Incorrect?

### ISSUE THREAD

**Issue by AlphonsGwatimba** [pdebuyl-lab/tidynamics#15]
The MSD result for two particles (in x, y coords) a  = (2, -2) and b = (0, -4) (`data=array([[ 2, -2], [ 0, -4]])`) should be `array([0.        , 1.37258301])` but instead `tidynamics.msd(data)` returns `array([0., 8.])`. I think the code is wrong?

**Comment by pdebuyl** [comment]
Hello,

Have you checked the storage scheme that is expected for tidynamics? It is explained at http://lab.pdebuyl.be/tidynamics/data_format.html

tidynamics works on single-particle trajectories where the first array index corresponds to time and the second to the spatial dimensions.

**Comment by AlphonsGwatimba** [comment]
> Hello,
> 
> Have you checked the storage scheme that is expected for tidynamics? It is explained at http://lab.pdebuyl.be/tidynamics/data_format.html
> 
> tidynamics works on single-particle trajectories where the first array index corresponds to time and the second to the spatial dimensions.

Hello, thank you for the fast response. I tried understanding this and I just cant dude I'm so sorry. I also messed up my example.. Lets say I wanted to calculate MSD of _one_ particle (so _one_ trajectory) which starts at (2, -2) and finishes at (0, -4) (x, y), how would the data array/code look like? Shouldn't there only be one MSD value which is 1.37258301? But I think tidynamics.msd is giving 8..

Thank you for you time

**Comment by pdebuyl** [comment]
The start point and the end point are separated by a square distance of `(x_1 - x_0)**2 + (y_1 - y_0)**2` which is `2**2 + 6**2 = 40`.

    x = np.array([[-2, 2], [0, -4]])
    msd = tidynamics.msd(x)
    print(msd)

returns `[ 0. 40.]`. By definition the MSD at time lag 0 (the first entry, indexed by 0, of the result of the msd routine) is always zero as the particle is at zero squared distance with its position at any equal time.

There are two time steps in the trajectory, so there is a result of length 2 (time lag 0 and time lag 1). The second value of the result is 40, the square distance between the point (-2,2) and (0,-4).

How do you obtain 1.37 ?

**Comment by AlphonsGwatimba** [comment]
Ohhhhh, I get it now! Thanks dude, I was doing MSD incorrectly, thank you! And thank you for this package :)

**Comment by pdebuyl** [comment]
You are welcome, thanks for the feedback!
