### ISSUE TITLE
More Examples

### ISSUE THREAD

**Issue by abhijeetdhakane** [pdebuyl-lab/tidynamics#16]
Do you mind to add realistic examples by taking MD trajectory data to compute MSD and VDOS?

**Comment by pdebuyl** [comment]
Hello @abhijeetdhakane , thank you for your interest in tidynamics :-) (and sorry for the delay, I was off most of the summer).

Can you be more specific about the MD data? tidynamics is rather simple on purpose, and I prefer for the content to remain generic. Adding examples, maybe without stored data, could be done if they remain concise enough though.

For the VDOS, I never computed it in my work and it is less common. Do you have an example in mind?
