### ISSUE TITLE
Import fails in package directory

### ISSUE THREAD

**Issue by malramsay64** [pdebuyl-lab/tidynamics#3]
From a fresh clone of the repository, importing tidynamics gives an error
```shell
$ git clone https://github.com/pdebuyl-lab/tidynamics
$ cd tidynamics
$ python -c "import tidynamics"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/malcolm/Documents/Programming/tidynamics/tidynamics/__init__.py", line 3, in <module>
    from .version import __version__ as __version__
ModuleNotFoundError: No module named 'tidynamics.version'
```

This finds the tidynamics module in the current directory, which doesn't have a version.py file since I haven't run setup.py. Either adding a try/except block around the import or item 3 from [this list](https://packaging.python.org/guides/single-sourcing-package-version/) are possible solutions.

**Comment by pdebuyl** [comment]
I will store the version number in a single file, `tidynamics/VERSION` and use it as the reference value.

**Comment by pdebuyl** [comment]
Done and tested with pip install, setup.py install and tidynamics imports properly from the repo.
