### ISSUE TITLE
[review] Improve API Documentation

### ISSUE THREAD

**Issue by malramsay64** [pdebuyl-lab/tidynamics#8]
I would consider the certain parts of the documentation to be inadequate for giving me a good grasp of using the API. As a reference for what I would expect, the documentation for the distance functions in [MDAnalysis](https://www.mdanalysis.org/docs/documentation_pages/analysis/distances.html) where there are few sentences providing helpful information on using the function. For explaining how to use the software I think your [RMPCDMD](http://lab.pdebuyl.be/rmpcdmd/algorithms.html) documentation does a good job.

Some specific points which I think need addressing:

- [x] The only information about the `tidynamics.cross_correlation` function is that it performs a cross correlation. Correlation and MSD is mentioned in the [Algorithms section](http://lab.pdebuyl.be/tidynamics/algorithms.html)
- [x] I find the documentation of the [data format](http://lab.pdebuyl.be/tidynamics/data_format.html) confusing. An example would go a long way in helping the explanation.
- [x] Have examples which are separate from the generation of the figures, since it is unclear what parts are for the figures and what is required to use the package. [This line](https://github.com/pdebuyl-lab/tidynamics/blob/3fc4f7b1b96f47eeb69f6fd0e9c57f25e795ea79/examples/plot_msd_1.py#L45) is a good example, do I need to discard half the results, or is that just for the figure.

**Comment by pdebuyl** [comment]
I added a part in "algorithms" to describe the `cross_displacement` function.

I edited both the documentation and the docstrings to improve the consistency. I don't know what to add to the dosctrings however, as the operations "autocorrelation" and "mean-square displacement" are standard and I do not provided options that change their behaviors, as it is the case in MDAnalysis' documentation.

I believe this addresses points 1 and 3. I am waiting for your feedback before doing 2.

**Comment by malramsay64** [comment]
Those changes look good.

For the docstrings, would adding something like the below to the mean squared displacement be appropriate?

    This function computes the MSD at each input time for the particle in the input 
    trajectory. Note that over short timescales this will give a slightly different 
    result to the standard method.

I haven't come across this particular algorithm before so I am not entirely sure what to put there, so feel free to change it. The idea being, what is useful for the person using the function? I completely understand that documentation is hard.

Now you have the two distinct input data types, `data` and `pos` the data format will be more easily differentiated. I think the important point about 2 is the first dimension being time, which I think is why I was initially confused since I am more used to it being a particle index.

**Comment by pdebuyl** [comment]
The method actually for the correlations and for the mean-square displacement gives identical result to the full-blown O(N²) computation. I will review once more the docstrings with the aim of "obviousness" :-)

Concerning 2, I will add an example to be completely specific.

**Comment by pdebuyl** [comment]
Update of [Data format](http://lab.pdebuyl.be/tidynamics/data_format.html)

**Comment by malramsay64** [comment]
I get it now :) The test comparing against to full computation is a great addition 👍 I was just comparing it to each point individually, hence the perceived difference.

As the documentation currently stands I think it is sufficient from the perspective of the review. It is definitely significantly easier to understand.

**Comment by pdebuyl** [comment]
Thank you for the feedback!
