### ISSUE TITLE
[review] Include matplotlib and pytest dependencies in instructions

### ISSUE THREAD

**Issue by malramsay64** [pdebuyl-lab/tidynamics#9]
The instructions for running the tests assume that the pytest pacakge is installed. Additionally the examples assume matplotlib is installed. I would consider a note with install instructions that these are required to be adequate.

**Comment by pdebuyl** [comment]
I think of adding a note on installing pytest next to 

> Testing
> We use pytest for testing:
> 
> python -m pytest

in the README and doc, and one on installing matplotlib in the text introducing the examples here: http://lab.pdebuyl.be/tidynamics/auto_examples/index.html This text is stored in `examples/README.txt` so it would be visible from the documentation as well as from the repository.

**Comment by malramsay64** [comment]
Sounds good to me.
